apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ei-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  rules:
  - host: wso2ei
    http:
      paths:
      - path: /healthcare
        backend:
          serviceName: demoei-service
          servicePort: 8253
